import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sample Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the{" "}
          <Link href="/posts/first-post">JavaScipt Universe</Link>
        </h1>

        <p className={styles.description}>Code your Future</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Software Development &rarr;</h2>
            <p>
              Become an expert coder who has experience working on live
              projects.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Project Management &rarr;</h2>
            <p>
              Our project management course molds you into an organization
              leader
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>UI/UX Design &rarr;</h2>
            <p>
              Website design, user interfaces, branding – you name it, we’ll
              cover it.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Blockchain &rarr;</h2>
            <p>
              Develop development skills in the fastest-growing tech sector.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
